import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Sparkles, FileText } from "lucide-react";
import { ProjectData, ConstraintsData } from "../DocumentWizard";
import { useToast } from "@/hooks/use-toast";

type Props = {
  projectData: ProjectData;
  files: File[];
  constraints: ConstraintsData;
  onNext: () => void;
  setIsGenerating: (val: boolean) => void;
  setGeneratedDoc: (doc: string) => void;
};

export const PreviewStep = ({ 
  projectData, 
  files, 
  constraints, 
  onNext, 
  setIsGenerating,
  setGeneratedDoc 
}: Props) => {
  const { toast } = useToast();

  const handleGenerate = async () => {
    setIsGenerating(true);
    onNext(); // Move to results page immediately
    
    toast({
      title: "Generating document...",
      description: "Please wait a moment",
    });

    // Simulate document generation
    setTimeout(() => {
      const mockDoc = generateMockDocument(projectData, constraints);
      setGeneratedDoc(mockDoc);
      setIsGenerating(false);
      toast({
        title: "Complete!",
        description: "Document generated successfully",
      });
    }, 3000);
  };

  const generateMockDocument = (data: ProjectData, constraints: ConstraintsData) => {
    return `# PROJECT DOCUMENTATION

## 1. PROJECT OVERVIEW
${data.overview}

${data.businessRequirements ? `## 2. BUSINESS REQUIREMENTS\n${data.businessRequirements}\n` : ''}
${data.functionalRequirements ? `## 3. FUNCTIONAL REQUIREMENTS\n${data.functionalRequirements}\n` : ''}
${data.nonFunctionalRequirements ? `## 4. NON-FUNCTIONAL REQUIREMENTS\n${data.nonFunctionalRequirements}\n` : ''}
${data.dataInfo ? `## 5. DATA INFORMATION\n${data.dataInfo}\n` : ''}
${data.deploymentInfo ? `## 6. DEPLOYMENT & ENVIRONMENT\n${data.deploymentInfo}\n` : ''}
${data.scheduleInfo ? `## 7. SCHEDULE & MANAGEMENT\n${data.scheduleInfo}\n` : ''}

---
*Document automatically generated by Document Generator*
*Detail level: ${constraints.depth} | Language: ${constraints.language}*`;
  };

  const languageLabel = {
    vietnamese: "Vietnamese",
    english: "English",
    both: "Bilingual"
  };

  const depthLabel = {
    brief: "Brief",
    medium: "Medium",
    detailed: "Detailed",
    comprehensive: "Comprehensive"
  };

  return (
    <div className="space-y-6">
      <div className="text-center space-y-2">
        <h2 className="text-2xl font-bold text-foreground">Preview & Confirm</h2>
        <p className="text-muted-foreground">
          Review information before generating document
        </p>
      </div>

      <Card className="p-6 bg-accent/50 space-y-4">
        <div>
          <h3 className="font-semibold text-foreground mb-3 flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            Project Information
          </h3>
          <div className="space-y-2 text-sm">
            <div>
              <span className="font-medium text-foreground">Overview:</span>
              <p className="text-muted-foreground mt-1">{projectData.overview}</p>
            </div>
            {projectData.businessRequirements && (
              <div>
                <span className="font-medium text-foreground">Business Requirements:</span>
                <p className="text-muted-foreground mt-1">{projectData.businessRequirements}</p>
              </div>
            )}
            {projectData.functionalRequirements && (
              <div>
                <span className="font-medium text-foreground">Functional Requirements:</span>
                <p className="text-muted-foreground mt-1">{projectData.functionalRequirements}</p>
              </div>
            )}
          </div>
        </div>

        <Separator />

        <div>
          <h3 className="font-semibold text-foreground mb-3">Attached Files</h3>
          {files.length > 0 ? (
            <div className="flex flex-wrap gap-2">
              {files.map((file, index) => (
                <Badge key={index} variant="secondary" className="px-3 py-1">
                  {file.name}
                </Badge>
              ))}
            </div>
          ) : (
            <p className="text-sm text-muted-foreground">No attached files</p>
          )}
        </div>

        <Separator />

        <div>
          <h3 className="font-semibold text-foreground mb-3">Settings</h3>
          <div className="flex flex-wrap gap-2">
            <Badge variant="outline" className="px-3 py-1">
              Language: {languageLabel[constraints.language as keyof typeof languageLabel]}
            </Badge>
            <Badge variant="outline" className="px-3 py-1">
              Detail: {depthLabel[constraints.depth as keyof typeof depthLabel]}
            </Badge>
          </div>
          {constraints.contentRequirements && (
            <p className="text-sm text-muted-foreground mt-2">
              Requirements: {constraints.contentRequirements}
            </p>
          )}
        </div>
      </Card>

      <Button
        onClick={handleGenerate}
        size="lg"
        className="w-full gap-2 bg-gradient-to-r from-primary to-primary/80 hover:from-primary/90 hover:to-primary/70"
      >
        <Sparkles className="w-5 h-5" />
        Generate Document
      </Button>
    </div>
  );
};
